### ISSUE TITLE
劳驾 告诉一下依赖库版本

### ISSUE THREAD

**Issue by Cary-yuyi** [yangwohenmai/LSTM#1]
请问作者tensorflow的版本号是多少？我用LSTM调了很久，效果都很差，不知道关键点在哪

**Comment by yangwohenmai** [comment]
我的tensorflow版本是1.13.1

**Comment by yangwohenmai** [comment]
你是在哪部分遇到的问题？

**Comment by Pan-will** [comment]
建模，找到了这里！！！作者给的代码非常友好！感谢，已star！

**Comment by yangwohenmai** [comment]
> 建模，找到了这里！！！作者给的代码非常友好！感谢，已star！

哈哈，谢谢，能有帮助就好
