### ISSUE TITLE
LSTM/stock_predict/stock_predict_2.py实现的不是预测功能 

### ISSUE THREAD

**Issue by llpspark** [yangwohenmai/LSTM#2]
你好，LSTM/stock_predict/stock_predict_2.py脚本中以batch内的数据和各自对应行的股价做label，并没有达到给予前time_step天预测下一天的作用

**Comment by yangwohenmai** [comment]
> 你好，LSTM/stock_predict/stock_predict_2.py脚本中以batch内的数据和各自对应行的股价做label，并没有达到给予前time_step天预测下一天的作用

确实，stock_predict只是我收集网上的一个项目，仅作参考，可以看看其他文件夹里的相关预测项目
