### ISSUE TITLE
关于LSTM预测结果滞后的问题

### ISSUE THREAD

**Issue by Zhujh0224** [yangwohenmai/LSTM#4]
你好，我想请教一下，我学习了一下LSTM多变量3这个完整的算例，结果看上去预测值会比实际值滞后一格，请问这是为什么。从代码上看标签都是取得数据重构后最后一列的数据，这个现象是正常的嘛。
![image](https://user-images.githubusercontent.com/92704247/138576889-fb9428f6-cbf1-42b9-a1c9-0623ea8abce7.png)
![image](https://user-images.githubusercontent.com/92704247/138576898-b26fa9f4-0a1c-47da-a57a-9500fbf6f3a7.png)

**Comment by ZP-Guo** [comment]
俺也一样，最近也碰到了这个问题

**Comment by yangwohenmai** [comment]
> 你好，我想请教一下，我学习了一下LSTM多变量3这个完整的算例，结果看上去预测值会比实际值滞后一格，请问这是为什么。从代码上看标签都是取得数据重构后最后一列的数据，这个现象是正常的嘛。 ![image](https://user-images.githubusercontent.com/92704247/138576889-fb9428f6-cbf1-42b9-a1c9-0623ea8abce7.png) ![image](https://user-images.githubusercontent.com/92704247/138576898-b26fa9f4-0a1c-47da-a57a-9500fbf6f3a7.png)

是正常的，主要原因是这是这个网络只是一个用于学习的基本的简单网络，以及训练数据集并不足够，并没有训练得到很好的效果。如果想进一步提高准确率，需要对网络模型进行进一步的优化

**Comment by yangwohenmai** [comment]
> 俺也一样，最近也碰到了这个问题

是正常的，主要原因是这是这个网络只是一个用于学习的基本的简单网络，以及训练数据集并不足够，并没有训练得到很好的效果。如果想进一步提高准确率，需要对网络模型进行进一步的优化

**Comment by Zhujh0224** [comment]
> > 你好，我想请教一下，我学习了一下LSTM多变量3这个完整的算例，结果看上去预测值会比实际值滞后一格，请问这是为什么。从代码上看标签都是取得数据重构后最后一列的数据，这个现象是正常的嘛。 ![image](https://user-images.githubusercontent.com/92704247/138576889-fb9428f6-cbf1-42b9-a1c9-0623ea8abce7.png) ![image](https://user-images.githubusercontent.com/92704247/138576898-b26fa9f4-0a1c-47da-a57a-9500fbf6f3a7.png)
> 
> 是正常的，主要原因是这是这个网络只是一个用于学习的基本的简单网络，以及训练数据集并不足够，并没有训练得到很好的效果。如果想进一步提高准确率，需要对网络模型进行进一步的优化

补充多问一下，主要的运行过程中最后计算得到的RMSE是根据这个错位结果来的，导致RMSE看上去挺大的。别的算例里面有训练数据集不足的，确实是看上去是简单的平移，这个算例初始的训练集是一年，我把它增加到两年三年好像也没有改善，麻烦请教一下训练集大概要是多少才能不出现这种现象。
另外，真的很感谢，算例讲得其实很清楚，有很多注释，算是我神经网络的入门学习资料了！

**Comment by yangwohenmai** [comment]
> 

仅仅去增加数据量，有用但也是不够的。要考虑从网络结构的调整，参数的优化，以及训练数据的特征工程入手。LSTM的本质是RNN，或多或少都会导致新数据比旧数据的权重大

**Comment by yangwohenmai** [comment]
> > > 你好，我想请教一下，我学习了一下LSTM多变量3这个完整的算例，结果看上去预测值会比实际值滞后一格，请问这是为什么。从代码上看标签都是取得数据重构后最后一列的数据，这个现象是正常的嘛。 ![image](https://user-images.githubusercontent.com/92704247/138576889-fb9428f6-cbf1-42b9-a1c9-0623ea8abce7.png) ![image](https://user-images.githubusercontent.com/92704247/138576898-b26fa9f4-0a1c-47da-a57a-9500fbf6f3a7.png)
> > 
> > 
> > 是正常的，主要原因是这是这个网络只是一个用于学习的基本的简单网络，以及训练数据集并不足够，并没有训练得到很好的效果。如果想进一步提高准确率，需要对网络模型进行进一步的优化
> 
> 补充多问一下，主要的运行过程中最后计算得到的RMSE是根据这个错位结果来的，导致RMSE看上去挺大的。别的算例里面有训练数据集不足的，确实是看上去是简单的平移，这个算例初始的训练集是一年，我把它增加到两年三年好像也没有改善，麻烦请教一下训练集大概要是多少才能不出现这种现象。 另外，真的很感谢，算例讲得其实很清楚，有很多注释，算是我神经网络的入门学习资料了！

仅仅去增加数据量，有用但也是不够的。要考虑从网络结构的调整，参数的优化，以及训练数据的特征工程入手。LSTM的本质是RNN，或多或少都会导致新数据比旧数据的权重大

**Comment by Efr0nd** [comment]
我最近刚学LSTM也遇到了这个问题，似乎LSTM模型本身就是有滞后性的。查了一下，可以通过增加特征维度或者改变模型的输入输出维度解决。想问一下楼主最终是怎么解决的？

**Comment by yangwohenmai** [comment]
> 我最近刚学LSTM也遇到了这个问题，似乎LSTM模型本身就是有滞后性的。查了一下，可以通过增加特征维度或者改变模型的输入输出维度解决。想问一下楼主最终是怎么解决的？

目前无法真正解决，只能通过增加特征维度有限的提升精确度

**Comment by Efr0nd** [comment]
> > 我最近刚学LSTM也遇到了这个问题，似乎LSTM模型本身就是有滞后性的。查了一下，可以通过增加特征维度或者改变模型的输入输出维度解决。想问一下楼主最终是怎么解决的？
> 
> 目前无法真正解决，只能通过增加特征维度有限的提升精确度

好的，感谢您的回复！
