### ISSUE TITLE
52行和55并没有用处吧？

### ISSUE THREAD

**Issue by haozewu** [yangwohenmai/LSTM#7]
https://github.com/yangwohenmai/LSTM/blob/432457dc73b1bca7a116a66e463f864bffade92c/LSTM%E7%B3%BB%E5%88%97/LSTM%E5%8D%95%E5%8F%98%E9%87%8F4/%E5%AE%8C%E6%95%B4%E7%9A%84LSTM%E6%A1%88%E4%BE%8B.py#L47-L57

shape本来就是这样的吧，看不懂这里的代码要做什么。

**Comment by yangwohenmai** [comment]
> https://github.com/yangwohenmai/LSTM/blob/432457dc73b1bca7a116a66e463f864bffade92c/LSTM%E7%B3%BB%E5%88%97/LSTM%E5%8D%95%E5%8F%98%E9%87%8F4/%E5%AE%8C%E6%95%B4%E7%9A%84LSTM%E6%A1%88%E4%BE%8B.py#L47-L57
> 
> shape本来就是这样的吧，看不懂这里的代码要做什么。

这两行代码没有用，当时只是希望做一个类型处理，可以忽略
