### ISSUE TITLE
关于数据重构问题

### ISSUE THREAD

**Issue by gjj1311923511** [yangwohenmai/LSTM#8]
您好，看了您的代码，受益匪浅，但是针对自己的问题，还有一些地方不太清楚，如果您有时间，希望你可以帮忙解答，万分感谢！
问题：现在网上很多的LSTM的实例讲解，大都是针对一列数据，如您代码中的乘客、香皂等。我现在想做的是一年内的每日降水，且我有三十个站点，这样的话，我的原始数据就是366*30的数据表，我想问一下，针对多条数据，在进行数据输入重构的时候应该怎么做？

**Comment by yangwohenmai** [comment]
> 您好，看了您的代码，受益匪浅，但是针对自己的问题，还有一些地方不太清楚，如果您有时间，希望你可以帮忙解答，万分感谢！ 问题：现在网上很多的LSTM的实例讲解，大都是针对一列数据，如您代码中的乘客、香皂等。我现在想做的是一年内的每日降水，且我有三十个站点，这样的话，我的原始数据就是366*30的数据表，我想问一下，针对多条数据，在进行数据输入重构的时候应该怎么做？

你想做多变量预测是吧，建议看看我的这个专栏，里面有三篇多变量预测的文章，应该能满足你，如果还有问题，可以继续来问

**Comment by yangwohenmai** [comment]
> 您好，看了您的代码，受益匪浅，但是针对自己的问题，还有一些地方不太清楚，如果您有时间，希望你可以帮忙解答，万分感谢！ 问题：现在网上很多的LSTM的实例讲解，大都是针对一列数据，如您代码中的乘客、香皂等。我现在想做的是一年内的每日降水，且我有三十个站点，这样的话，我的原始数据就是366*30的数据表，我想问一下，针对多条数据，在进行数据输入重构的时候应该怎么做？

你想做多变量预测是吧，建议看看我的这个专栏，里面有三篇多变量预测的文章，应该能满足你，如果还有问题，可以继续来问。专栏链接：https://forecast.blog.csdn.net/article/details/84568510

**Comment by gjj1311923511** [comment]
万分感谢，昨天在您的GitHub代码库中找到一个例子，貌似可以解决我现在的困惑。如果后续还有问题，希望您不吝赐教！




(7K15X6)&nbsp;活动中心
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yangwohenmai/LSTM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月21日(星期四) 下午3:43
***@***.***&gt;;
抄送:&nbsp;"(7K15X6) ***@***.******@***.***&gt;;
主题:&nbsp;Re: [yangwohenmai/LSTM] 关于数据重构问题 (Issue #8)





  
您好，看了您的代码，受益匪浅，但是针对自己的问题，还有一些地方不太清楚，如果您有时间，希望你可以帮忙解答，万分感谢！ 问题：现在网上很多的LSTM的实例讲解，大都是针对一列数据，如您代码中的乘客、香皂等。我现在想做的是一年内的每日降水，且我有三十个站点，这样的话，我的原始数据就是366*30的数据表，我想问一下，针对多条数据，在进行数据输入重构的时候应该怎么做？
  
你想做多变量预测是吧，建议看看我的这个专栏，里面有三篇多变量预测的文章，应该能满足你，如果还有问题，可以继续来问。专栏链接：https://forecast.blog.csdn.net/article/details/84568510

**Comment by gjj1311923511** [comment]
冒昧再次打扰您！
您好，我现在训练模型跑通了，但是又遇到一个问题，如果可以的话，还得麻烦您解答。
问题：就像之前邮件描述的，我现在是用三十个站点去训练模型，所以我的lstm的输入就reshape为[363,3,30],但是我现在想要做的是用这训练好的模型，去得到更多的站点（多余30个，比如有200个）预测。如果是200个站点，则输入的reshape应该就是[363,3,200]，此时就会出现输入不匹配的问题。请问我该怎么解决这个问题。
我的目的就是要去实现如图片中描述：





(7K15X6)&nbsp;活动中心
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yangwohenmai/LSTM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月21日(星期四) 下午3:43
***@***.***&gt;;
抄送:&nbsp;"(7K15X6) ***@***.******@***.***&gt;;
主题:&nbsp;Re: [yangwohenmai/LSTM] 关于数据重构问题 (Issue #8)





  
您好，看了您的代码，受益匪浅，但是针对自己的问题，还有一些地方不太清楚，如果您有时间，希望你可以帮忙解答，万分感谢！ 问题：现在网上很多的LSTM的实例讲解，大都是针对一列数据，如您代码中的乘客、香皂等。我现在想做的是一年内的每日降水，且我有三十个站点，这样的话，我的原始数据就是366*30的数据表，我想问一下，针对多条数据，在进行数据输入重构的时候应该怎么做？
  
你想做多变量预测是吧，建议看看我的这个专栏，里面有三篇多变量预测的文章，应该能满足你，如果还有问题，可以继续来问。专栏链接：https://forecast.blog.csdn.net/article/details/84568510

**Comment by yangwohenmai** [comment]
> 冒昧再次打扰您！ 您好，我现在训练模型跑通了，但是又遇到一个问题，如果可以的话，还得麻烦您解答。 问题：就像之前邮件描述的，我现在是用三十个站点去训练模型，所以我的lstm的输入就reshape为[363,3,30],但是我现在想要做的是用这训练好的模型，去得到更多的站点（多余30个，比如有200个）预测。如果是200个站点，则输入的reshape应该就是[363,3,200]，此时就会出现输入不匹配的问题。请问我该怎么解决这个问题。 我的目的就是要去实现如图片中描述： (7K15X6)&nbsp;活动中心 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "yangwohenmai/LSTM" ***@***.***&gt;; 发送时间:&nbsp;2022年7月21日(星期四) 下午3:43 ***@***.***&gt;; 抄送:&nbsp;"(7K15X6) ***@***.******@***.***&gt;; 主题:&nbsp;Re: [yangwohenmai/LSTM] 关于数据重构问题 (Issue #8) 您好，看了您的代码，受益匪浅，但是针对自己的问题，还有一些地方不太清楚，如果您有时间，希望你可以帮忙解答，万分感谢！ 问题：现在网上很多的LSTM的实例讲解，大都是针对一列数据，如您代码中的乘客、香皂等。我现在想做的是一年内的每日降水，且我有三十个站点，这样的话，我的原始数据就是366*30的数据表，我想问一下，针对多条数据，在进行数据输入重构的时候应该怎么做？ 你想做多变量预测是吧，建议看看我的这个专栏，里面有三篇多变量预测的文章，应该能满足你，如果还有问题，可以继续来问。专栏链接：https://forecast.blog.csdn.net/article/details/84568510 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

这个问题是一开始输入数据的结构设计的不合理造成的。[363,3,30]意味着有363个sample，每个sample有30个特征值，每组数据步长为3，根据你描述的数据场景，这种输入结构并不合适。特征值不应该用站点的数量，而是用每个站点监测数据所包含的数据特征

**Comment by gjj1311923511** [comment]
很抱歉再次打扰你，我这几天看了很多网上的教程，但是依旧没有成功，我觉得应该还是数据整理的问题。如果您有时间，能不能帮我实现一下数据重构的代码，万分感谢！！！
文件第一行是站点号，第一列是日期。




(7K15X6)&nbsp;活动中心
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yangwohenmai/LSTM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月22日(星期五) 下午3:54
***@***.***&gt;;
抄送:&nbsp;"(7K15X6) ***@***.******@***.***&gt;;
主题:&nbsp;Re: [yangwohenmai/LSTM] 关于数据重构问题 (Issue #8)





  
冒昧再次打扰您！ 您好，我现在训练模型跑通了，但是又遇到一个问题，如果可以的话，还得麻烦您解答。 问题：就像之前邮件描述的，我现在是用三十个站点去训练模型，所以我的lstm的输入就reshape为[363,3,30],但是我现在想要做的是用这训练好的模型，去得到更多的站点（多余30个，比如有200个）预测。如果是200个站点，则输入的reshape应该就是[363,3,200]，此时就会出现输入不匹配的问题。请问我该怎么解决这个问题。 我的目的就是要去实现如图片中描述： (7K15X6)&nbsp;活动中心 @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "yangwohenmai/LSTM" @.&gt;; 发送时间:&nbsp;2022年7月21日(星期四) 下午3:43 @.&gt;; 抄送:&nbsp;"(7K15X6) @.@.&gt;; 主题:&nbsp;Re: [yangwohenmai/LSTM] 关于数据重构问题 (Issue #8) 您好，看了您的代码，受益匪浅，但是针对自己的问题，还有一些地方不太清楚，如果您有时间，希望你可以帮忙解答，万分感谢！ 问题：现在网上很多的LSTM的实例讲解，大都是针对一列数据，如您代码中的乘客、香皂等。我现在想做的是一年内的每日降水，且我有三十个站点，这样的话，我的原始数据就是36630的数据表，我想问一下，针对多条数据，在进行数据输入重构的时候应该怎么做？ 你想做多变量预测是吧，建议看看我的这个专栏，里面有三篇多变量预测的文章，应该能满足你，如果还有问题，可以继续来问。专栏链接：https://forecast.blog.csdn.net/article/details/84568510 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.**&gt;
  
这个问题是一开始输入数据的结构设计的不合理造成的。[363,3,30]意味着有363个sample，每个sample有30个特征值，每组数据步长为3，根据你描述的数据场景，这种输入结构并不合适。特征值不应该用站点的数量，而是用每个站点监测数据所包含的数据特征

**Comment by lidaban233** [comment]
> 

您好，我也在做降水量预测工作，可以发邮件1181973726@qq.com和我交流
